all: Kill Prottemp Prottemp_mejorado Prottemp_mejorado_op Lect_escr

Kill: ejercicio_kill.c
	gcc -o Kill ejercicio_kill.c

Prottemp:
	gcc -o Prottemp ejercicio_prottemp.c

Prottemp_mejorado:
	gcc -pthread -o Prottemp_mejorado ejercicio_prottemp_mejorado.c

Prottemp_mejorado_op:
	gcc -pthread -o Prottemp_mejorado_op ejercicio_prottemp_mejorado_op.c

Lect_escr:
	gcc -pthread -o Lect_escr ejercicio_lect_escr.c
