all: Hilos Arbol Shell Shell_spawn Pipes

Hilos: ejercicio_hilos.c
	gcc  -pthread -o Hilos ejercicio_hilos.c

Arbol: ejercicio_arbol.c
	gcc -o Arbol ejercicio_arbol.c

Shell: ejercicio_shell.c
	gcc -o Shell ejercicio_shell.c

Shell_spawn: ejercicio_shell_spawn.c
	gcc -o Shell_spawn ejercicio_shell_spawn.c

Pipes: ejercicio_pipes.c
	gcc -o Pipes ejercicio_pipes.c
